const PHRASE_MINIMUM_WORD_COUNT = 3;
const PHRASE_MAXIMUM_WORD_COUNT = 10;

const PHRASE_MINIMUM_FREQUENCY_COUNT = 1;
const PHRASE_MAXIMUM_OUTPUT_COUNT = 10;

module.exports = {
  PHRASE_MINIMUM_WORD_COUNT,
  PHRASE_MAXIMUM_WORD_COUNT,
  PHRASE_MINIMUM_FREQUENCY_COUNT,
  PHRASE_MAXIMUM_OUTPUT_COUNT,
};
